remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: MWAsplund GitHub Pages
description: Matthew Asplund's github pages site used to contain my thoughts and projects I wish to share with others.